openapi: 3.0.0
info:
  description: 配置服务API
  license:
    name: Apache-2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  title: 配置服务API
  version: 1.0.0
servers:
- url: https://api.lucfish.com/configuration/v1
security:
- ApiKey: []
paths:
  /config:
    post:
      description: 创建配置
      operationId: createConfig
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateConfigReq'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateConfigResponse'
          description: successful operation
        "405":
          description: Invalid input
      summary: 创建配置
      tags:
      - Config
    put:
      description: 更新配置，需要全部的配置信息
      operationId: updateConfig
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateConfigReq'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateConfigResponse'
          description: successful operation
        "405":
          description: Invalid input
      summary: 更新配置
      tags:
      - Config
  /config/{id}:
    delete:
      description: 删除配置
      operationId: deleteConfig
      parameters:
      - description: 删除配置
        explode: false
        in: path
        name: id
        required: true
        schema:
          format: string
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteResponse'
          description: successful operation
        "405":
          description: Invalid input
      summary: 删除配置
      tags:
      - Config
    get:
      description: 查询配置通过配置ID
      operationId: getConfig
      parameters:
      - description: 查询配置通过配置ID
        explode: false
        in: path
        name: id
        required: true
        schema:
          format: string
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetConfigResponse'
          description: successful operation
        "405":
          description: Invalid input
      summary: 查询配置
      tags:
      - Config
  /config/batchRetrieve:
    post:
      description: 批量查询配置通过配置Id
      operationId: batchRetrieveConfigs
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IdsReq'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchRetrieveConfigsResponse'
          description: successful operation
        "405":
          description: Invalid input
      summary: 批量查询配置
      tags:
      - Config
  /config/batchDelete:
    post:
      description: 批量删除配置通过配置Id
      operationId: batchDeleteConfigs
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IdsReq'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteResponse'
          description: successful operation
        "405":
          description: Invalid input
      summary: 批量删除配置
      tags:
      - Config
  /config/page:
    post:
      description: Page查询配置
      operationId: pageConfigs
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PageQuery'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageConfigsResponse'
          description: successful operation
        "405":
          description: Invalid input
      summary: Page查询配置
      tags:
      - Config
  /config/cursor:
    post:
      description: Cursor查询配置
      operationId: cursorConfigs
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CursorQuery'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CursorConfigsResponse'
          description: successful operation
        "405":
          description: Invalid input
      summary: Cursor查询配置
      tags:
      - Config
  /config/retrieveByKey:
    post:
      description: 查询配置通过配置Key和资源ID
      operationId: retrieveByKeyConfig
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RetrieveConfigByKeyReq'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetrieveConfigByKeyResponse'
          description: successful operation
        "405":
          description: Invalid input
      summary: 查询配置
      tags:
      - Config
  /config/batchRetrieveByKeys:
    post:
      description: 查询配置通过配置Keys和资源ID
      operationId: batchRetrieveByKeysConfigs
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BatchRetrieveByKeysReq'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchRetrieveConfigsByKeysResponse'
          description: successful operation
        "405":
          description: Invalid input
      summary: 查询配置
      tags:
      - Config
  /config/batchRetrieveByResources:
    post:
      description: 查询配置通过配置GroupID
      operationId: batchRetrieveByResourcesConfigs
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BatchRetrieveByResourcesReq'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchRetrieveConfigsByResourcesResponse'
          description: successful operation
        "405":
          description: Invalid input
      summary: 查询配置
      tags:
      - Config
  /configTemplate:
    post:
      description: 创建配置模版
      operationId: createConfigTemplate
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateConfigTemplateReq'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateConfigTemplateResponse'
          description: successful operation
        "405":
          description: Invalid input
      summary: 创建配置模版
      tags:
      - ConfigTemplate
    put:
      description: 更新配置模版，需要全部的配置模版信息
      operationId: updateConfigTemplate
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateConfigTemplateReq'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateConfigTemplateResponse'
          description: successful operation
        "405":
          description: Invalid input
      summary: 更新配置模版
      tags:
      - Config
  /configTemplate/{id}:
    delete:
      description: 删除配置模版
      operationId: deleteConfigTemplate
      parameters:
      - description: 删除配置模版
        explode: false
        in: path
        name: id
        required: true
        schema:
          format: string
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteResponse'
          description: successful operation
        "405":
          description: Invalid input
      summary: 删除配置模版
      tags:
      - ConfigTemplate
    get:
      description: 查询配置通过配置模版ID
      operationId: getConfigTemplate
      parameters:
      - description: 查询配置通过配置ID
        explode: false
        in: path
        name: id
        required: true
        schema:
          format: string
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetConfigTemplateResponse'
          description: successful operation
        "405":
          description: Invalid input
      summary: 查询配置模版
      tags:
      - ConfigTemplate
  /configTemplate/batchRetrieve:
    post:
      description: 批量查询配置模版通过配置Id
      operationId: batchRetrieveConfigTemplates
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IdsReq'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchRetrieveConfigTemplatesResponse'
          description: successful operation
        "405":
          description: Invalid input
      summary: 批量查询配置模版
      tags:
      - ConfigTemplate
  /configTemplate/batchDelete:
    post:
      description: 批量删除配置模版通过配置Id
      operationId: batchDeleteConfigTemplates
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IdsReq'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteResponse'
          description: successful operation
        "405":
          description: Invalid input
      summary: 批量删除配置模版
      tags:
      - ConfigTemplate
  /configTemplate/page:
    post:
      description: Page查询配置模版
      operationId: pageConfigTemplate
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PageQuery'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageConfigTemplatesResponse'
          description: successful operation
        "405":
          description: Invalid input
      summary: Page查询配置模版
      tags:
      - ConfigTemplate
  /configTemplate/cursor:
    post:
      description: Cursor查询配置模版
      operationId: cursorConfigTemplates
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CursorQuery'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CursorConfigTemplatesResponse'
          description: successful operation
        "405":
          description: Invalid input
      summary: Cursor查询配置模版
      tags:
      - ConfigTemplate
  /configTemplate/retrieveByKey:
    post:
      description: 查询配置模版通过配置Key
      operationId: retrieveByKeyConfigTemplate
      parameters:
      - description: 主键Key
        explode: true
        in: query
        name: key
        required: true
        schema:
          format: string
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetrieveConfigTemplateByKeyResponse'
          description: successful operation
        "405":
          description: Invalid input
      summary: 查询配置模版
      tags:
      - ConfigTemplate
  /configTemplate/batchRetrieveByKeys:
    post:
      description: 查询配置通过配置Keys
      operationId: batchRetrieveByKeysConfigTemplates
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BatchRetrieveConfigTemplateByKeysReq'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchRetrieveConfigTemplatesByKeysResponse'
          description: successful operation
        "405":
          description: Invalid input
      summary: 查询配置模版
      tags:
      - ConfigTemplate
  /configTemplate/batchRetrieveByGroup:
    post:
      description: 查询配置模版通过配置模版GroupID
      operationId: batchRetrieveByGroupConfigTemplates
      parameters:
      - description: 分组标签名
        explode: true
        in: query
        name: groupName
        required: true
        schema:
          format: string
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchRetrieveConfigTemplatesByGroupResponse'
          description: successful operation
        "405":
          description: Invalid input
      summary: 查询配置模版
      tags:
      - ConfigTemplate
  /configGroup:
    post:
      description: 创建组
      operationId: createGroup
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateConfigGroupReq'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateConfigGroupResponse'
          description: successful operation
        "405":
          description: Invalid input
      summary: 创建组
      tags:
      - ConfigGroup
    put:
      description: 更新组，需要全部的组信息
      operationId: updateGroup
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateConfigGroupReq'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateConfigGroupResponse'
          description: successful operation
        "405":
          description: Invalid input
      summary: 更新组
      tags:
      - ConfigGroup
  /configGroup/{id}:
    delete:
      description: 删除组
      operationId: deleteGroup
      parameters:
      - description: 删除组
        explode: false
        in: path
        name: id
        required: true
        schema:
          format: string
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteResponse'
          description: successful operation
        "405":
          description: Invalid input
      summary: 删除组
      tags:
      - ConfigGroup
    get:
      description: 查询组通过组ID
      operationId: getGroup
      parameters:
      - description: 查询组通过组ID
        explode: false
        in: path
        name: id
        required: true
        schema:
          format: string
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetConfigGroupResponse'
          description: successful operation
        "405":
          description: Invalid input
      summary: 查询组
      tags:
      - ConfigGroup
  /configGroup/batchRetrieve:
    post:
      description: 批量查询组通过组Id
      operationId: batchRetrieveGroups
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IdsReq'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchRetrieveConfigGroupsResponse'
          description: successful operation
        "405":
          description: Invalid input
      summary: 批量查询组
      tags:
      - ConfigGroup
  /configGroup/batchDelete:
    post:
      description: 批量删除组通过组Id
      operationId: batchDeleteGroups
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IdsReq'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteResponse'
          description: successful operation
        "405":
          description: Invalid input
      summary: 批量删除组
      tags:
      - ConfigGroup
  /configGroup/page:
    post:
      description: Page查询组
      operationId: pageGroups
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PageQuery'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageConfigGroupsResponse'
          description: successful operation
        "405":
          description: Invalid input
      summary: Page查询组
      tags:
      - ConfigGroup
  /configGroup/cursor:
    post:
      description: Cursor查询组
      operationId: cursorGroups
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CursorQuery'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CursorConfigGroupsResponse'
          description: successful operation
        "405":
          description: Invalid input
      summary: Cursor查询组
      tags:
      - ConfigGroup
  /configGroup/retrieveByName:
    post:
      description: 查询组通过Name
      operationId: retrieveByNameGroup
      parameters:
      - description: 查询组通过Name
        explode: true
        in: query
        name: name
        required: true
        schema:
          format: string
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetrieveConfigGroupByNameResponse'
          description: successful operation
        "405":
          description: Invalid input
      summary: 查询组
      tags:
      - ConfigGroup
components:
  schemas:
    IdsReq:
      example:
        ids:
        - ids
        - ids
      properties:
        ids:
          description: 配置ID列表
          items:
            format: string
            type: string
          type: array
      type: object
    BatchRetrieveConfigsResponse:
      example:
        ids:
        - ids
        - ids
      properties:
        ids:
          description: 配置ID列表
          items:
            format: string
            type: string
          type: array
      type: object
    RetrieveConfigByKeyReq:
      example:
        msg: msg
        code: 0
        data:
        - resourceId: resourceId
          groupId: groupId
          ctime: 6
          id: id
          templateId: templateId
          mtime: 1
          value: '{}'
          key: key
        - resourceId: resourceId
          groupId: groupId
          ctime: 6
          id: id
          templateId: templateId
          mtime: 1
          value: '{}'
          key: key
      properties:
        code:
          format: int64
          type: integer
        msg:
          format: string
          type: string
        data:
          items:
            $ref: '#/components/schemas/Config'
          type: array
      type: object
    RetrieveConfigByKeyResponse:
      example:
        msg: msg
        code: 0
        data:
          resourceId: resourceId
          groupId: groupId
          ctime: 6
          id: id
          templateId: templateId
          mtime: 1
          value: '{}'
          key: key
      properties:
        code:
          format: int64
          type: integer
        msg:
          format: string
          type: string
        data:
          $ref: '#/components/schemas/Config'
      type: object
    BatchRetrieveByKeysReq:
      example:
        resourceId: resourceId
        keys:
        - keys
        - keys
      properties:
        keys:
          description: keys
          items:
            type: string
          type: array
        resourceId:
          description: 资源ID
          format: string
          type: string
      type: object
    BatchRetrieveConfigsByKeysResponse:
      example:
        msg: msg
        code: 0
        data:
        - resourceId: resourceId
          groupId: groupId
          ctime: 6
          id: id
          templateId: templateId
          mtime: 1
          value: '{}'
          key: key
        - resourceId: resourceId
          groupId: groupId
          ctime: 6
          id: id
          templateId: templateId
          mtime: 1
          value: '{}'
          key: key
      properties:
        code:
          format: int64
          type: integer
        msg:
          format: string
          type: string
        data:
          items:
            $ref: '#/components/schemas/Config'
          type: array
      type: object
    BatchRetrieveByResourcesReq:
      example:
        key: key
        resourceIds:
        - resourceIds
        - resourceIds
      properties:
        key:
          description: key
          format: string
          type: string
        resourceIds:
          description: 资源ID组
          items:
            type: string
          type: array
      type: object
    BatchRetrieveConfigsByResourcesResponse:
      example:
        msg: msg
        code: 0
        data:
        - resourceId: resourceId
          groupId: groupId
          ctime: 6
          id: id
          templateId: templateId
          mtime: 1
          value: '{}'
          key: key
        - resourceId: resourceId
          groupId: groupId
          ctime: 6
          id: id
          templateId: templateId
          mtime: 1
          value: '{}'
          key: key
      properties:
        code:
          format: int64
          type: integer
        msg:
          format: string
          type: string
        data:
          items:
            $ref: '#/components/schemas/Config'
          type: array
      type: object
    BatchRetrieveConfigTemplateByKeysReq:
      example:
        keys:
        - keys
        - keys
      properties:
        keys:
          items:
            type: string
          type: array
      type: object
    BatchRetrieveConfigTemplateByKeysResponse:
      properties:
        keys:
          items:
            type: string
          type: array
      type: object
    CursorQuery:
      example:
        cursor: cursor
        cursorSort: ""
        size: 0
        filters: '{}'
        direction: 6
      properties:
        filters:
          description: 查询条件，传键值对
          type: object
        cursor:
          description: 游标值
          format: string
          type: string
        cursorSort:
          description: 排序 $ref:"#/components/schemas/SortSpec"
        size:
          description: 大小
          format: int64
          type: integer
        direction:
          description: 查询方向，0表示游标前，1表示游标后
          format: byte
          type: integer
      type: object
    CursorExtra:
      example:
        resourceId: resourceId
        size: 6
        direction: 1
      properties:
        size:
          description: 大小
          format: int64
          type: integer
        direction:
          description: 查询方向，0表示游标前，1表示游标后
          format: byte
          type: integer
        resourceId:
          description: 资源ID
          format: string
          type: string
      type: object
    CreateConfigReq:
      example:
        resourceId: resourceId
        groupId: groupId
        templateId: templateId
        value: '{}'
        key: key
      properties:
        resourceId:
          description: 资源ID
          format: string
          type: string
        groupId:
          description: 组ID
          format: string
          type: string
        templateId:
          description: 模版ID
          format: string
          type: string
        key:
          description: 对应的字段名
          format: string
          type: string
        value:
          description: json格式的键值对数据
          type: object
      type: object
    CreateConfigResponse:
      example:
        msg: msg
        code: 0
        data:
          resourceId: resourceId
          groupId: groupId
          ctime: 6
          id: id
          templateId: templateId
          mtime: 1
          value: '{}'
          key: key
      properties:
        code:
          format: int64
          type: integer
        msg:
          format: string
          type: string
        data:
          $ref: '#/components/schemas/Config'
      type: object
    UpdateConfigReq:
      example:
        id: id
        value: '{}'
      properties:
        id:
          description: 配置ID
          format: string
          type: string
        value:
          description: json格式的键值对数据
          type: object
      type: object
    UpdateConfigResponse:
      example:
        msg: msg
        code: 0
        data:
          resourceId: resourceId
          groupId: groupId
          ctime: 6
          id: id
          templateId: templateId
          mtime: 1
          value: '{}'
          key: key
      properties:
        code:
          format: int64
          type: integer
        msg:
          format: string
          type: string
        data:
          $ref: '#/components/schemas/Config'
      type: object
    GetConfigResponse:
      example:
        msg: msg
        code: 0
        data:
          resourceId: resourceId
          groupId: groupId
          ctime: 6
          id: id
          templateId: templateId
          mtime: 1
          value: '{}'
          key: key
      properties:
        code:
          format: int64
          type: integer
        msg:
          format: string
          type: string
        data:
          $ref: '#/components/schemas/Config'
      type: object
    PageConfigsResponse:
      example:
        msg: msg
        code: 0
        data:
          pageCount: 5
          total: 5
          pageNo: 6
          pageSize: 1
          content:
          - resourceId: resourceId
            groupId: groupId
            ctime: 6
            id: id
            templateId: templateId
            mtime: 1
            value: '{}'
            key: key
          - resourceId: resourceId
            groupId: groupId
            ctime: 6
            id: id
            templateId: templateId
            mtime: 1
            value: '{}'
            key: key
      properties:
        code:
          format: int64
          type: integer
        msg:
          format: string
          type: string
        data:
          $ref: '#/components/schemas/PageConfigsResponse_data'
      type: object
    CursorConfigsResponse:
      example:
        msg: msg
        code: 0
        data:
          extra:
            resourceId: resourceId
            size: 6
            direction: 1
          items:
          - resourceId: resourceId
            groupId: groupId
            ctime: 6
            id: id
            templateId: templateId
            mtime: 1
            value: '{}'
            key: key
          - resourceId: resourceId
            groupId: groupId
            ctime: 6
            id: id
            templateId: templateId
            mtime: 1
            value: '{}'
            key: key
      properties:
        code:
          format: int64
          type: integer
        msg:
          format: string
          type: string
        data:
          $ref: '#/components/schemas/CursorConfigsResponse_data'
      type: object
    Config:
      example:
        resourceId: resourceId
        groupId: groupId
        ctime: 6
        id: id
        templateId: templateId
        mtime: 1
        value: '{}'
        key: key
      properties:
        id:
          description: 配置ID
          format: string
          type: string
        resourceId:
          description: 资源ID
          format: string
          type: string
        groupId:
          description: 组ID
          format: string
          type: string
        templateId:
          description: 模版ID
          format: string
          type: string
        key:
          description: 对应的字段名
          format: string
          type: string
        value:
          description: json格式的键值对数据
          type: object
        ctime:
          description: 创建时间，返回时间戳
          format: int64
          type: integer
        mtime:
          description: 更新时间，返回时间戳
          format: int64
          type: integer
      type: object
    CreateConfigGroupReq:
      example:
        name: name
      properties:
        name:
          description: 名称
          format: string
          type: string
      type: object
    CreateConfigGroupResponse:
      example:
        msg: msg
        code: 0
        data:
          name: name
          ctime: 6
          id: id
          mtime: 1
      properties:
        code:
          format: int64
          type: integer
        msg:
          format: string
          type: string
        data:
          $ref: '#/components/schemas/ConfigGroup'
      type: object
    UpdateConfigGroupReq:
      example:
        name: name
        id: id
      properties:
        id:
          description: 配置ID
          format: string
          type: string
        name:
          description: 名称
          type: string
      type: object
    UpdateConfigGroupResponse:
      example:
        msg: msg
        code: 0
        data:
          name: name
          ctime: 6
          id: id
          mtime: 1
      properties:
        code:
          format: int64
          type: integer
        msg:
          format: string
          type: string
        data:
          $ref: '#/components/schemas/ConfigGroup'
      type: object
    GetConfigGroupResponse:
      example:
        msg: msg
        code: 0
        data:
          name: name
          ctime: 6
          id: id
          mtime: 1
      properties:
        code:
          format: int64
          type: integer
        msg:
          format: string
          type: string
        data:
          $ref: '#/components/schemas/ConfigGroup'
      type: object
    BatchRetrieveConfigGroupsResponse:
      example:
        msg: msg
        code: 0
        data:
        - name: name
          ctime: 6
          id: id
          mtime: 1
        - name: name
          ctime: 6
          id: id
          mtime: 1
      properties:
        code:
          format: int64
          type: integer
        msg:
          format: string
          type: string
        data:
          items:
            $ref: '#/components/schemas/ConfigGroup'
          type: array
      type: object
    PageConfigGroupsResponse:
      example:
        msg: msg
        code: 0
        data:
          pageCount: 5
          total: 5
          pageNo: 6
          pageSize: 1
          content:
          - name: name
            ctime: 6
            id: id
            mtime: 1
          - name: name
            ctime: 6
            id: id
            mtime: 1
      properties:
        code:
          format: int64
          type: integer
        msg:
          format: string
          type: string
        data:
          $ref: '#/components/schemas/PageConfigGroupsResponse_data'
      type: object
    CursorConfigGroupsResponse:
      example:
        msg: msg
        code: 0
        data:
          extra:
            resourceId: resourceId
            size: 6
            direction: 1
          items:
          - name: name
            ctime: 6
            id: id
            mtime: 1
          - name: name
            ctime: 6
            id: id
            mtime: 1
      properties:
        code:
          format: int64
          type: integer
        msg:
          format: string
          type: string
        data:
          $ref: '#/components/schemas/CursorConfigGroupsResponse_data'
      type: object
    RetrieveConfigGroupByNameResponse:
      example:
        msg: msg
        code: 0
        data:
          name: name
          ctime: 6
          id: id
          mtime: 1
      properties:
        code:
          format: int64
          type: integer
        msg:
          format: string
          type: string
        data:
          $ref: '#/components/schemas/ConfigGroup'
      type: object
    ConfigGroup:
      example:
        name: name
        ctime: 6
        id: id
        mtime: 1
      properties:
        id:
          description: 配置ID
          format: string
          type: string
        name:
          description: 名称
          format: string
          type: string
        ctime:
          description: 创建时间，返回时间戳
          format: int64
          type: integer
        mtime:
          description: 更新时间，返回时间戳
          format: int64
          type: integer
      type: object
    CreateConfigTemplateReq:
      example:
        groupId: groupId
        templateId: templateId
        value: '{}'
        key: key
      properties:
        groupId:
          description: 组ID
          format: string
          type: string
        templateId:
          description: 模版ID
          format: string
          type: string
        key:
          description: 对应的字段名
          format: string
          type: string
        value:
          description: json格式的键值对数据
          type: object
      type: object
    CreateConfigTemplateResponse:
      example:
        msg: msg
        code: 0
        data:
          groupId: groupId
          ctime: 6
          id: id
          templateId: templateId
          mtime: 1
          value: '{}'
          key: key
      properties:
        code:
          format: int64
          type: integer
        msg:
          format: string
          type: string
        data:
          $ref: '#/components/schemas/ConfigTemplate'
      type: object
    UpdateConfigTemplateReq:
      example:
        id: id
        value: '{}'
      properties:
        id:
          description: 配置ID
          format: string
          type: string
        value:
          description: json格式的键值对数据
          type: object
      type: object
    UpdateConfigTemplateResponse:
      example:
        msg: msg
        code: 0
        data:
          groupId: groupId
          ctime: 6
          id: id
          templateId: templateId
          mtime: 1
          value: '{}'
          key: key
      properties:
        code:
          format: int64
          type: integer
        msg:
          format: string
          type: string
        data:
          $ref: '#/components/schemas/ConfigTemplate'
      type: object
    GetConfigTemplateResponse:
      example:
        msg: msg
        code: 0
        data:
          groupId: groupId
          ctime: 6
          id: id
          templateId: templateId
          mtime: 1
          value: '{}'
          key: key
      properties:
        code:
          format: int64
          type: integer
        msg:
          format: string
          type: string
        data:
          $ref: '#/components/schemas/ConfigTemplate'
      type: object
    BatchRetrieveConfigTemplatesResponse:
      example:
        msg: msg
        code: 0
        data:
        - groupId: groupId
          ctime: 6
          id: id
          templateId: templateId
          mtime: 1
          value: '{}'
          key: key
        - groupId: groupId
          ctime: 6
          id: id
          templateId: templateId
          mtime: 1
          value: '{}'
          key: key
      properties:
        code:
          format: int64
          type: integer
        msg:
          format: string
          type: string
        data:
          items:
            $ref: '#/components/schemas/ConfigTemplate'
          type: array
      type: object
    PageConfigTemplatesResponse:
      example:
        msg: msg
        code: 0
        data:
          pageCount: 5
          total: 5
          pageNo: 6
          pageSize: 1
          content:
          - groupId: groupId
            ctime: 6
            id: id
            templateId: templateId
            mtime: 1
            value: '{}'
            key: key
          - groupId: groupId
            ctime: 6
            id: id
            templateId: templateId
            mtime: 1
            value: '{}'
            key: key
      properties:
        code:
          format: int64
          type: integer
        msg:
          format: string
          type: string
        data:
          $ref: '#/components/schemas/PageConfigTemplatesResponse_data'
      type: object
    CursorConfigTemplatesResponse:
      example:
        msg: msg
        code: 0
        data:
          extra:
            resourceId: resourceId
            size: 6
            direction: 1
          items:
          - groupId: groupId
            ctime: 6
            id: id
            templateId: templateId
            mtime: 1
            value: '{}'
            key: key
          - groupId: groupId
            ctime: 6
            id: id
            templateId: templateId
            mtime: 1
            value: '{}'
            key: key
      properties:
        code:
          format: int64
          type: integer
        msg:
          format: string
          type: string
        data:
          $ref: '#/components/schemas/CursorConfigTemplatesResponse_data'
      type: object
    RetrieveConfigTemplateByKeyResponse:
      example:
        msg: msg
        code: 0
        data:
          groupId: groupId
          ctime: 6
          id: id
          templateId: templateId
          mtime: 1
          value: '{}'
          key: key
      properties:
        code:
          format: int64
          type: integer
        msg:
          format: string
          type: string
        data:
          $ref: '#/components/schemas/ConfigTemplate'
      type: object
    BatchRetrieveConfigTemplatesByKeysResponse:
      example:
        msg: msg
        code: 0
        data:
        - groupId: groupId
          ctime: 6
          id: id
          templateId: templateId
          mtime: 1
          value: '{}'
          key: key
        - groupId: groupId
          ctime: 6
          id: id
          templateId: templateId
          mtime: 1
          value: '{}'
          key: key
      properties:
        code:
          format: int64
          type: integer
        msg:
          format: string
          type: string
        data:
          items:
            $ref: '#/components/schemas/ConfigTemplate'
          type: array
      type: object
    BatchRetrieveConfigTemplatesByGroupResponse:
      example:
        msg: msg
        code: 0
        data:
        - groupId: groupId
          ctime: 6
          id: id
          templateId: templateId
          mtime: 1
          value: '{}'
          key: key
        - groupId: groupId
          ctime: 6
          id: id
          templateId: templateId
          mtime: 1
          value: '{}'
          key: key
      properties:
        code:
          format: int64
          type: integer
        msg:
          format: string
          type: string
        data:
          items:
            $ref: '#/components/schemas/ConfigTemplate'
          type: array
      type: object
    ConfigTemplate:
      example:
        groupId: groupId
        ctime: 6
        id: id
        templateId: templateId
        mtime: 1
        value: '{}'
        key: key
      properties:
        id:
          description: 配置ID
          format: string
          type: string
        groupId:
          description: 组ID
          format: string
          type: string
        templateId:
          description: 模版ID
          format: string
          type: string
        key:
          description: 对应的字段名
          format: string
          type: string
        value:
          description: json格式的键值对数据
          type: object
        ctime:
          description: 创建时间，返回时间戳
          format: int64
          type: integer
        mtime:
          description: 更新时间，返回时间戳
          format: int64
          type: integer
      type: object
    PageQuery:
      example:
        pageNo: 0
        pageSize: 6
        filters: '{}'
        sort:
        - ignoreCase: ignoreCase
          property: property
          type: type
        - ignoreCase: ignoreCase
          property: property
          type: type
      properties:
        filters:
          description: 查询条件，传键值对
          type: object
        pageNo:
          description: 页码
          format: int32
          type: integer
        pageSize:
          description: 每页数据量
          format: int32
          type: integer
        sort:
          description: 排序
          items:
            $ref: '#/components/schemas/SortSpec'
          type: array
      type: object
    SortSpec:
      example:
        ignoreCase: ignoreCase
        property: property
        type: type
      properties:
        property:
          description: 排序字段
          format: string
          type: string
        type:
          description: 排序类型，0默认，1升序，2降序
          format: string
          type: string
        ignoreCase:
          description: 是否忽略大小写
          format: string
          type: string
      type: object
    DeleteResponse:
      example:
        msg: msg
        code: 0
        data: ""
      properties:
        code:
          format: int64
          type: integer
        msg:
          format: string
          type: string
        data:
          description: 暂时未返回数据
      type: object
    PageConfigsResponse_data:
      example:
        pageCount: 5
        total: 5
        pageNo: 6
        pageSize: 1
        content:
        - resourceId: resourceId
          groupId: groupId
          ctime: 6
          id: id
          templateId: templateId
          mtime: 1
          value: '{}'
          key: key
        - resourceId: resourceId
          groupId: groupId
          ctime: 6
          id: id
          templateId: templateId
          mtime: 1
          value: '{}'
          key: key
      properties:
        pageNo:
          description: 页码
          format: int32
          type: integer
        pageSize:
          description: 翻页大小
          format: int32
          type: integer
        pageCount:
          description: 页数
          format: int32
          type: integer
        total:
          description: 总数量
          format: int32
          type: integer
        content:
          items:
            $ref: '#/components/schemas/Config'
          type: array
    CursorConfigsResponse_data:
      example:
        extra:
          resourceId: resourceId
          size: 6
          direction: 1
        items:
        - resourceId: resourceId
          groupId: groupId
          ctime: 6
          id: id
          templateId: templateId
          mtime: 1
          value: '{}'
          key: key
        - resourceId: resourceId
          groupId: groupId
          ctime: 6
          id: id
          templateId: templateId
          mtime: 1
          value: '{}'
          key: key
      properties:
        extra:
          $ref: '#/components/schemas/CursorExtra'
        items:
          items:
            $ref: '#/components/schemas/Config'
          type: array
    PageConfigGroupsResponse_data:
      example:
        pageCount: 5
        total: 5
        pageNo: 6
        pageSize: 1
        content:
        - name: name
          ctime: 6
          id: id
          mtime: 1
        - name: name
          ctime: 6
          id: id
          mtime: 1
      properties:
        pageNo:
          description: 页码
          format: int32
          type: integer
        pageSize:
          description: 翻页大小
          format: int32
          type: integer
        pageCount:
          description: 页数
          format: int32
          type: integer
        total:
          description: 总数量
          format: int32
          type: integer
        content:
          items:
            $ref: '#/components/schemas/ConfigGroup'
          type: array
    CursorConfigGroupsResponse_data:
      example:
        extra:
          resourceId: resourceId
          size: 6
          direction: 1
        items:
        - name: name
          ctime: 6
          id: id
          mtime: 1
        - name: name
          ctime: 6
          id: id
          mtime: 1
      properties:
        extra:
          $ref: '#/components/schemas/CursorExtra'
        items:
          items:
            $ref: '#/components/schemas/ConfigGroup'
          type: array
    PageConfigTemplatesResponse_data:
      example:
        pageCount: 5
        total: 5
        pageNo: 6
        pageSize: 1
        content:
        - groupId: groupId
          ctime: 6
          id: id
          templateId: templateId
          mtime: 1
          value: '{}'
          key: key
        - groupId: groupId
          ctime: 6
          id: id
          templateId: templateId
          mtime: 1
          value: '{}'
          key: key
      properties:
        pageNo:
          description: 页码
          format: int32
          type: integer
        pageSize:
          description: 翻页大小
          format: int32
          type: integer
        pageCount:
          description: 页数
          format: int32
          type: integer
        total:
          description: 总数量
          format: int32
          type: integer
        content:
          items:
            $ref: '#/components/schemas/ConfigTemplate'
          type: array
    CursorConfigTemplatesResponse_data:
      example:
        extra:
          resourceId: resourceId
          size: 6
          direction: 1
        items:
        - groupId: groupId
          ctime: 6
          id: id
          templateId: templateId
          mtime: 1
          value: '{}'
          key: key
        - groupId: groupId
          ctime: 6
          id: id
          templateId: templateId
          mtime: 1
          value: '{}'
          key: key
      properties:
        extra:
          $ref: '#/components/schemas/CursorExtra'
        items:
          items:
            $ref: '#/components/schemas/ConfigTemplate'
          type: array
  securitySchemes:
    ApiKey:
      scheme: bearer
      type: http
